# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_15_DAYS_OF_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Day 02: Version control(1).json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 02: Version control.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 03: Debugging.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 04: Authorization.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 05: Variables and scripts.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 06: API tests.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 07: Run test suites.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 08: Output test results(1).json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 08: Output test results.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 09: API workflows.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 10: Test coverage.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 11: Validation.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 12: Use libraries.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 13: Mock servers.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 14: More tests.json" -e "29142931-ae08936d-17cd-45ba-adb3-05411526f905"
          postman collection run "${{ github.workspace }}/postman/collections/Day 15: Submit for badge.json" -e "29142931-1b13f979-4b33-48c6-a149-9ccf5458f14e"
          postman collection run "${{ github.workspace }}/postman/collections/mockForTesting.json"
          postman collection run "${{ github.workspace }}/postman/collections/The Good Bank APIs.json" 
         
